#!/bin/bash

usage() {
    echo "Usage: $0 -h --pfam <pfam_id> --min-length <min_length> --max-length <max_length> --clust-th <similarity_threshold> --hmm-name <hmm_name>"
    echo ""
    echo "Options:"
    echo "  -h: show the usage message"
    echo "  --pfam <pfam_id>: Specify the PFAM ID"
    echo "  --min-length <min_length>: Specify the minimum length (default 0)"
    echo "  --max-length <max_length>: Specify the maximum length (default 1000)"
    echo "  --clust-th <similarity_threshold>: Specify the similarity cutoff for clustering (default 100)" 
    echo "  --hmm-name <hmm_name> (default 'model')"
    echo ""
    exit 1
}

# Default values
pfam_id=""
min_length=0
max_length=1000
clust_th=100
hmm_name="model"

if [[ $# -eq 0 ]]
then
    usage
    exit 1
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h )
            usage
            exit 1
            ;;
        --pfam )
            pfam_id="$2"
            shift 2
            ;;
        --min-length )
            min_length="$2"
            shift 2
            ;;
        --max-length )
            max_length="$2"
            shift 2
            ;;
        --clust-th )
            clust_th="$2"
            shift 2
            ;;
        --hmm-name )
            hmm_name="$2"
            shift 2
            ;;
        *)
            echo "Invalid option: $1" 1>&2
            usage
            exit 1
            ;;
    esac
done

RED='\033[0;31m'
NC='\033[0m'
if [[ -z $pfam_id ]]; then
    echo -e "${RED}Error: --pfam option is required.$NC\n"
    usage
fi

printf "\n# Running with options:\n"
echo "#     PFAM ID: $pfam_id"
echo "#     Minimum length: $min_length"
echo "#     Maximum length: $max_length"
echo "#     Clustering threshold: $clust_th"
echo "#     HMM file name: $hmm_name"
echo "#"


./clean.sh

./msta.sh $pfam_id $min_length $max_length $clust_th

./hmm_build.sh $hmm_name

./get_sets.sh $pfam_id

./split_train_test.sh 

./match.sh $hmm_name

./cross_validation.sh 

#./evaluate.sh